import { describe, it, expect } from '@jest/globals';
import { generateTypes, schemaToType, toTypeName, escapePropertyName } from '../generate-types.js';
import type { GenerateTypesOptions } from '../generate-types.js';

// ─── Helpers ────────────────────────────────────────────────────────

async function generateFromMockServer(
  extraOptions?: Partial<GenerateTypesOptions>
): Promise<string> {
  return generateTypes({
    command: 'node',
    args: ['./examples/mock-server.js'],
    timeout: 15000,
    ...extraOptions,
  });
}

// ─── End-to-End Tests ───────────────────────────────────────────────

describe('generateTypes — e2e', () => {
  it('should generate a valid TypeScript declaration file', async () => {
    const output = await generateFromMockServer();
    expect(output).toContain('export interface EchoArgs');
    expect(output).toContain('export interface AddArgs');
    expect(output).toContain('export type ToolName');
    expect(output).toContain('export interface ToolArgsMap');
    expect(output).toContain('export type ResourceUri');
    expect(output).toContain('export type PromptName');
    expect(output).toContain('export interface PromptArgsMap');
    expect(output).toContain('export interface ServerCapabilities');
  });

  it('should include tool descriptions as JSDoc', async () => {
    const output = await generateFromMockServer();
    expect(output).toContain('/** Echo back the input */');
    expect(output).toContain('/** Add two numbers */');
  });

  it('should include property descriptions as JSDoc', async () => {
    const output = await generateFromMockServer();
    expect(output).toContain('/** Message to echo */');
  });

  it('should generate correct ToolName union', async () => {
    const output = await generateFromMockServer();
    expect(output).toMatch(/'echo'.*'add'.*'delay'.*'error_tool'/s);
  });

  it('should generate ToolArgsMap with all tools', async () => {
    const output = await generateFromMockServer();
    expect(output).toContain("'echo': EchoArgs");
    expect(output).toContain("'add': AddArgs");
    expect(output).toContain("'delay': DelayArgs");
    expect(output).toContain("'error_tool': ErrorToolArgs");
  });

  it('should generate ToolCall discriminated union', async () => {
    const output = await generateFromMockServer();
    expect(output).toContain('export type ToolCall =');
    expect(output).toContain("{ name: 'echo'; arguments: EchoArgs }");
    expect(output).toContain("{ name: 'add'; arguments: AddArgs }");
  });

  it('should generate ResourceUri type', async () => {
    const output = await generateFromMockServer();
    expect(output).toContain("'text://example'");
    expect(output).toContain("'config://settings'");
  });

  it('should generate PromptName union', async () => {
    const output = await generateFromMockServer();
    expect(output).toContain("'greet' | 'summarize'");
  });

  it('should generate prompt argument interfaces', async () => {
    const output = await generateFromMockServer();
    expect(output).toContain('export interface GreetArgs');
    expect(output).toContain('name: string');
    expect(output).toContain('export interface SummarizeArgs');
    expect(output).toContain('text: string');
  });

  it('should generate PromptCall discriminated union', async () => {
    const output = await generateFromMockServer();
    expect(output).toContain('export type PromptCall =');
    expect(output).toContain("{ name: 'greet'; arguments: GreetArgs }");
  });

  it('should include header with server info', async () => {
    const output = await generateFromMockServer();
    expect(output).toContain('TypeScript types generated from MCP server');
    expect(output).toContain('Server: node');
    expect(output).toContain('Generated by @slbdn/mcp-tester');
  });

  it('should include ServerCapabilities interface', async () => {
    const output = await generateFromMockServer();
    expect(output).toContain('export interface ServerCapabilities');
    expect(output).toContain('tools: ToolName[]');
    expect(output).toContain('resources: ResourceUri[]');
    expect(output).toContain('prompts: PromptName[]');
  });
});

// ─── Options Tests ──────────────────────────────────────────────────

describe('generateTypes — options', () => {
  it('should skip resources with includeResources=false', async () => {
    const output = await generateFromMockServer({ includeResources: false });
    expect(output).not.toContain('ResourceUri');
    expect(output).not.toContain('Resource URI Types');
  });

  it('should skip prompts with includePrompts=false', async () => {
    const output = await generateFromMockServer({ includePrompts: false });
    expect(output).not.toContain('PromptName');
    expect(output).not.toContain('PromptArgsMap');
    expect(output).not.toContain('Prompt Argument Types');
  });

  it('should use custom module name in examples', async () => {
    const output = await generateFromMockServer({ moduleName: 'my-tester' });
    expect(output).toContain("import { MCPClient } from 'my-tester'");
  });

  it('should throw on invalid command', async () => {
    await expect(
      generateTypes({
        command: 'nonexistent-command-that-does-not-exist',
        timeout: 5000,
      })
    ).rejects.toThrow();
  });
});

// ─── schemaToType Unit Tests ────────────────────────────────────────

describe('schemaToType', () => {
  describe('primitives', () => {
    it('should convert string', () => {
      expect(schemaToType({ type: 'string' })).toBe('string');
    });

    it('should convert number', () => {
      expect(schemaToType({ type: 'number' })).toBe('number');
    });

    it('should convert integer to number', () => {
      expect(schemaToType({ type: 'integer' })).toBe('number');
    });

    it('should convert boolean', () => {
      expect(schemaToType({ type: 'boolean' })).toBe('boolean');
    });

    it('should convert null', () => {
      expect(schemaToType({ type: 'null' })).toBe('null');
    });

    it('should return unknown for unknown type', () => {
      expect(schemaToType({ type: 'custom' })).toBe('unknown');
    });
  });

  describe('enum', () => {
    it('should convert string enum to union', () => {
      expect(schemaToType({ enum: ['a', 'b', 'c'] })).toBe("'a' | 'b' | 'c'");
    });

    it('should convert mixed enum', () => {
      expect(schemaToType({ enum: ['yes', 1, true] })).toBe("'yes' | 1 | true");
    });

    it('should convert single-value enum', () => {
      expect(schemaToType({ enum: ['only'] })).toBe("'only'");
    });
  });

  describe('const', () => {
    it('should convert string const', () => {
      expect(schemaToType({ const: 'hello' })).toBe("'hello'");
    });

    it('should convert number const', () => {
      expect(schemaToType({ const: 42 })).toBe('42');
    });

    it('should convert boolean const', () => {
      expect(schemaToType({ const: true })).toBe('true');
    });
  });

  describe('array', () => {
    it('should convert string array', () => {
      expect(schemaToType({ type: 'array', items: { type: 'string' } })).toBe('string[]');
    });

    it('should convert number array', () => {
      expect(schemaToType({ type: 'array', items: { type: 'number' } })).toBe('number[]');
    });

    it('should convert object array to Array<T>', () => {
      const result = schemaToType({
        type: 'array',
        items: { type: 'object', properties: { x: { type: 'number' } }, required: ['x'] },
      });
      expect(result).toContain('Array<');
      expect(result).toContain('x: number');
    });

    it('should convert tuple items', () => {
      const result = schemaToType({
        type: 'array',
        items: [{ type: 'string' }, { type: 'number' }],
      });
      expect(result).toBe('[string, number]');
    });

    it('should default to unknown[] without items', () => {
      expect(schemaToType({ type: 'array' })).toBe('unknown[]');
    });
  });

  describe('object', () => {
    it('should convert object with required and optional fields', () => {
      const result = schemaToType({
        type: 'object',
        properties: {
          name: { type: 'string' },
          age: { type: 'number' },
        },
        required: ['name'],
      });
      expect(result).toContain('name: string');
      expect(result).toContain('age?: number');
    });

    it('should handle empty properties', () => {
      expect(schemaToType({ type: 'object', properties: {} })).toBe('Record<string, unknown>');
    });

    it('should handle no properties', () => {
      expect(schemaToType({ type: 'object' })).toBe('Record<string, unknown>');
    });

    it('should handle additionalProperties', () => {
      const result = schemaToType({
        type: 'object',
        additionalProperties: { type: 'string' },
      });
      expect(result).toBe('Record<string, string>');
    });

    it('should handle nested objects', () => {
      const result = schemaToType({
        type: 'object',
        properties: {
          config: {
            type: 'object',
            properties: {
              host: { type: 'string' },
              port: { type: 'number' },
            },
            required: ['host', 'port'],
          },
        },
        required: ['config'],
      });
      expect(result).toContain('config: {');
      expect(result).toContain('host: string');
      expect(result).toContain('port: number');
    });

    it('should escape special property names', () => {
      const result = schemaToType({
        type: 'object',
        properties: {
          'my-field': { type: 'string' },
          'data.json': { type: 'string' },
        },
        required: ['my-field', 'data.json'],
      });
      expect(result).toContain("'my-field': string");
      expect(result).toContain("'data.json': string");
    });
  });

  describe('compositions', () => {
    it('should convert oneOf to union', () => {
      const result = schemaToType({
        oneOf: [{ type: 'string' }, { type: 'number' }],
      });
      expect(result).toBe('string | number');
    });

    it('should convert anyOf to union', () => {
      const result = schemaToType({
        anyOf: [{ type: 'string' }, { type: 'boolean' }],
      });
      expect(result).toBe('string | boolean');
    });

    it('should convert allOf to intersection', () => {
      const result = schemaToType({
        allOf: [
          {
            type: 'object',
            properties: { name: { type: 'string' } },
            required: ['name'],
          },
          {
            type: 'object',
            properties: { age: { type: 'number' } },
            required: ['age'],
          },
        ],
      });
      expect(result).toContain('&');
      expect(result).toContain('name: string');
      expect(result).toContain('age: number');
    });
  });

  describe('$ref', () => {
    it('should extract type name from $ref', () => {
      expect(schemaToType({ $ref: '#/definitions/MyType' })).toBe('MyType');
    });

    it('should extract from nested $ref path', () => {
      expect(schemaToType({ $ref: '#/components/schemas/User' })).toBe('User');
    });
  });

  describe('edge cases', () => {
    it('should handle empty schema', () => {
      expect(schemaToType({})).toBe('unknown');
    });

    it('should handle implicit object (properties without type)', () => {
      const result = schemaToType({
        properties: { x: { type: 'number' } },
        required: ['x'],
      });
      expect(result).toContain('x: number');
    });

    it('should include JSDoc from description', () => {
      const result = schemaToType({
        type: 'object',
        properties: {
          name: { type: 'string', description: 'The name' },
        },
        required: ['name'],
      });
      expect(result).toContain('/** The name */');
    });
  });
});

// ─── toTypeName Unit Tests ──────────────────────────────────────────

describe('toTypeName', () => {
  it('should capitalize first letter', () => {
    expect(toTypeName('echo')).toBe('Echo');
  });

  it('should handle snake_case', () => {
    expect(toTypeName('my_tool')).toBe('MyTool');
  });

  it('should handle kebab-case', () => {
    expect(toTypeName('error-tool')).toBe('ErrorTool');
  });

  it('should handle already PascalCase', () => {
    expect(toTypeName('MyTool')).toBe('Mytool');
  });

  it('should handle multi-separator names', () => {
    expect(toTypeName('get-user-by-id')).toBe('GetUserById');
  });

  it('should handle single character', () => {
    expect(toTypeName('x')).toBe('X');
  });
});

// ─── escapePropertyName Unit Tests ──────────────────────────────────

describe('escapePropertyName', () => {
  it('should not quote simple identifiers', () => {
    expect(escapePropertyName('name')).toBe('name');
  });

  it('should not quote underscore identifiers', () => {
    expect(escapePropertyName('_name')).toBe('_name');
  });

  it('should not quote dollar identifiers', () => {
    expect(escapePropertyName('$name')).toBe('$name');
  });

  it('should quote hyphenated names', () => {
    expect(escapePropertyName('my-field')).toBe("'my-field'");
  });

  it('should quote names with dots', () => {
    expect(escapePropertyName('data.json')).toBe("'data.json'");
  });

  it('should escape single quotes in name', () => {
    expect(escapePropertyName("it's")).toBe("'it\\'s'");
  });
});
